// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCluCgOgVJZsIVNfMjpCxUh7uxjRKFrHAA',
    appId: '1:498582721163:web:01509c5413debaef877a8e',
    messagingSenderId: '498582721163',
    projectId: 'weather-flutter-9b578',
    authDomain: 'weather-flutter-9b578.firebaseapp.com',
    storageBucket: 'weather-flutter-9b578.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4gEdp9L_bV_nq50xnZCcLGFEaex52vUY',
    appId: '1:498582721163:android:ac17d9013875dea3877a8e',
    messagingSenderId: '498582721163',
    projectId: 'weather-flutter-9b578',
    storageBucket: 'weather-flutter-9b578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXT7ArlQc_wD_-2DHiR14FQOkjCv2VotQ',
    appId: '1:498582721163:ios:45de565e0ff7d93d877a8e',
    messagingSenderId: '498582721163',
    projectId: 'weather-flutter-9b578',
    storageBucket: 'weather-flutter-9b578.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXT7ArlQc_wD_-2DHiR14FQOkjCv2VotQ',
    appId: '1:498582721163:ios:45de565e0ff7d93d877a8e',
    messagingSenderId: '498582721163',
    projectId: 'weather-flutter-9b578',
    storageBucket: 'weather-flutter-9b578.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCluCgOgVJZsIVNfMjpCxUh7uxjRKFrHAA',
    appId: '1:498582721163:web:69b04775f9c2cf2e877a8e',
    messagingSenderId: '498582721163',
    projectId: 'weather-flutter-9b578',
    authDomain: 'weather-flutter-9b578.firebaseapp.com',
    storageBucket: 'weather-flutter-9b578.appspot.com',
  );
}
