class CityData {
  static List<String> cities = [
    'New York',
    'Paris',
    'Tokyo',
    'Sydney',
    'London',
    'Los Angeles',
    'Berlin',
    'Beijing',
    'Moscow',
    'Rio de Janeiro',
    'Mumbai',
    'Rome',
    'Cairo',
    'Toronto',
    'Dubai',
    'Singapore',
    'New Delhi',
    'Mumbai',
    'Bangalore',
    'Kolkata',
    'Chennai',
    'Hyderabad',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Surat',
    'Kanpur',
    'Lucknow',
    'Nagpur',
    'Indore',
    'Thane',
    'Bhopal',
    'Visakhapatnam',
    'Pimpri-Chinchwad',
    'Patna',
    'Vadodara',
    'Ghaziabad',
    'Ludhiana',
    'Agra',
    'Nashik',
    'Faridabad',
    'Meerut',
    'Rajkot',
    'Kalyan-Dombivli',
    'Vasai-Virar',
    'Varanasi',
    'Srinagar',
    'Aurangabad',
    'Dhanbad',
    'Amritsar',
    'Navi Mumbai',
    'Allahabad',
    'Howrah',
    'Ranchi',
    'Gwalior',
    'Jabalpur',
    'Coimbatore',
    'Vijayawada',
    'Jodhpur',
    'Madurai',
    'Raipur',
    'Kota',
    'Guwahati',
    'Chandigarh',
    'Hubli-Dharwad',
    'Mysore',
    'Tiruchirappalli',
    'Bareilly',
    'Aligarh',
    'Tiruppur',
    'Gurgaon',
    'Moradabad',
    'Jalandhar',
    'Bhubaneswar',
    'Salem',
    'Warangal',
    'Guntur',
    'Bhiwandi',
    'Saharanpur',
    'Gorakhpur',
    'Bikaner',
    'Amravati',
    'Noida',
    'Jamshedpur',
    'Bhilai',
    'Cuttack',
    'Firozabad',
    'Kochi',
    'Nellore',
    'Bhavnagar',
    // Other cities from India
    'Agartala',
    'Itanagar',
    'Kohima',
    'Imphal',
    'Aizawl',
    'Panaji',
    'Shimla',
    'Srinagar',
    'Gangtok',
    'Chandigarh',
    // Other major cities from around the world
    'Washington D.C.',
    'Los Angeles',
    'Chicago',
    'Toronto',
    'Mexico City',
    'Buenos Aires',
    'São Paulo',
    'London',
    'Paris',
    'Berlin',
    'Madrid',
    'Moscow',
    'Rome',
    'Athens',
    'Cairo',
    'Sydney',
    'Tokyo',
    'Beijing',
    'Seoul',
    'Bangkok',
    'Singapore',
    'Dubai',
    'Mumbai',
    'New Delhi',
    'Karachi',
    'Istanbul',
    'Dhaka',
    'Jakarta',
    'Manila',
    'Kuala Lumpur',
    'Hanoi',
    'Ho Chi Minh City',
    'Sydney',
    'Melbourne',
    'Auckland',
    'Johannesburg',
    'Cape Town',
    'Nairobi',
    'Rio de Janeiro',
    'Santiago',
    'Bogotá',
    'Lima',
    'Mexico City',
    'New York City',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Francisco',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Washington D.C.',
    'Boston',
    'El Paso',
    'Detroit',
    'Nashville',
    'Memphis',
    'Portland',
    'Oklahoma City',
    'Las Vegas',
    'Louisville',
    'Baltimore',
    'Milwaukee',
    'Albuquerque',
    'Tucson',
    'Fresno',
    'Sacramento',
    'Kansas City',
    'Long Beach',
    'Mesa',
    'Atlanta',
    'Colorado Springs',
    'Virginia Beach',
    'Raleigh',
    'Omaha',
    'Miami',
    'Oakland',
    'Minneapolis',
    'Tulsa',
    'Wichita',
    'New Orleans',
    'Arlington',
    'Cleveland',
    'Bakersfield',
    'Tampa',
    'Aurora',
    'Honolulu',
    'Anaheim',
    'Santa Ana',
    'Riverside',
    'Corpus Christi',
    'Lexington',
    'Stockton',
    'St. Paul',
    'Cincinnati',
    'St. Louis',
    'Pittsburgh',
    'Greensboro',
    'Lincoln',
    'Anchorage',
    'Plano',
    'Orlando',
    'Irvine',
    'Newark',
    'Durham',
    'Chula Vista',
    'Toledo',
    'Fort Wayne',
    'St. Petersburg',
    'Laredo',
    'Jersey City',
    'Chandler',
    'Madison',
    'Lubbock',
    'Scottsdale',
    'Reno',
    'Buffalo',
    'Gilbert',
    'Glendale',
    'North Las Vegas',
    'Winston-Salem',
    'Chesapeake',
    'Norfolk',
    'Fremont',
    'Garland',
    'Irving',
    'Hialeah',
    'Boise',
    'Richmond',
    'Baton Rouge',
    'Spokane',
    'Des Moines',
    'Tacoma',
    'San Bernardino',
    'Modesto',
    'Fontana',
    'Santa Clarita',
    'Birmingham',
    'Oxnard',
    'Fayetteville',
    'Rochester',
    'Moreno Valley',
    'Glendale',
    'Yonkers',
    'Huntington Beach',
    'Arlington',
    'Salt Lake City',
    'Montgomery',
    'Amarillo',
    'Aurora',
    'Grand Rapids',
    'Little Rock',
    'Akron',
    'Mobile',
    'Huntsville',
    'Augusta',
    'Port St. Lucie',
    'Grand Prairie',
    'Columbus',
    'Tallahassee',
    'Overland Park',
    'Tempe',
    'McKinney',
    'Mobile',
    'Cape Coral',
    'Shreveport',
    'Frisco',
    'Knoxville',
    'Worcester',
    'Brownsville',
    'Vancouver',
    'Fort Lauderdale',
    'Sioux Falls',
    'Ontario',
    'Chattanooga',
    'Providence',
    'Newport News',
    'Santa Rosa',
    'Oceanside',
    'Salem',
    'Elk Grove',
    'Garden Grove',
    'Pembroke Pines',
    'Eugene',
    'Peoria',
    'Corona',
    'Cary',
    'Springfield',
    'Fort Collins',
    'Jackson',
    'Alexandria',
    'Hayward',
    'Lancaster',
    'Lakewood',
    'Salinas',
    'Palmdale',
    'Springfield',
    'Sunnyvale',
    'Hollywood',
    'Pasadena',
    'Macon',
    'Killeen',
    'Naperville',
    'Joliet',
    'Bellevue',
    'Miramar',
    'Coral Springs',
    'Olathe',
    'Sterling Heights',
    'Fullerton',
    'Thornton',
    'West Valley City',
    'Topeka',
    'New Haven',
    'Oceanside',
    'Waco',
    'Charleston',
    'Cedar Rapids',
    'Sterling Heights',
    'Gainesville',
    'Visalia',
    'Coral Springs',
    'Thousand Oaks',
    'Elizabeth',
    'Stamford',
    'Concord',
    'Roseville',
    'Simi Valley',
    'Lafayette',
    'Hartford',
    'Cedar Rapids',
    'Thornton',
    'Kent',
    'Surprise',
    'Evansville',
    'Midland',
    'Santa Clara',
    'Athens',
    'Allentown',
    'Norman',
    'Beaumont',
    'Independence',
    'Murfreesboro',
    'Ann Arbor',
    'Springfield',
    'Berkeley',
    'Peoria',
    'El Monte',
    'Abilene',
    'Knoxville',
    'Columbia',
    'Lansing',
    'Fargo',
    'Downey',
    'Costa Mesa',
    'Wilmington',
    'Arvada',
    'Inglewood',
    'Miami Gardens',
    'Carlsbad',
    'Westminster',
    'Rochester',
    'Odessa',
    'Manchester',
    'Elgin',
    'West Jordan',
    'Round Rock',
    'Clearwater',
    'Waterbury',
    'Gresham',
    'Fairfield',
    'Billings',
    'Lowell',
    'San Buenaventura (Ventura)',
    'Pueblo',
    'High Point',
    'West Covina',
    'Richmond',
    'Murrieta',
    'Cambridge',
    'Antioch',
    'Temecula',
    'Norwalk',
    'Centennial',
    'Everett',
    'Palm Bay',
    'Wichita Falls',
    'Green Bay',
    'Daly City',
    'Burbank',
    'Richardson',
    'Pompano Beach',
    'North Charleston',
    'Broken Arrow',
    'Boulder',
    'West Palm Beach',
    'Santa Maria',
    'El Cajon',
    'Davenport',
    'Rialto',
    'Las Cruces',
    'San Mateo',
    'Lewisville',
    'South Bend',
    'Lakeland',
    'Erie',
    'Tyler',
    'Pearland',
    'College Station',
    'Kenosha',
    'Sandy Springs',
    'Clovis',
    'Flint',
    'Roanoke',
    'Albany',
    'Jurupa Valley',
    'Compton',
    'San Angelo',
    'Hillsboro',
    'Lawton',
    'Renton',
    'Vista',
    'Davie',
    'Greeley',
    'Mission Viejo',
    'Portsmouth',
    'Dearborn',
    'South Gate',
    'Tuscaloosa',
    'Livonia',
    'New Bedford',
    'Vacaville',
    'Brockton',
    'Roswell',
    'Beaverton',
    'Quincy',
    'Sparks',
    'Yakima',
    'Lee\'s Summit',
    'Federal Way',
    'Carson',
    'Santa Monica',
    'Hesperia',
    'Allen',
    'Rio Rancho',
    'Yuma',
    'Westminster',
    'Orem',
    'Lynn',
    'Redding',
    'Spokane Valley',
    'Miami Beach',
    'League City',
    'Lawrence',
    'Santa Barbara',
    'Plantation',
    'Sandy',
    'Sunrise',
    'Macon',
    'Longmont',
    'Boca Raton',
    'San Marcos',
    'Greenville',
    'Waukegan',
    'Fall River',
    'Chico',
    'Newton',
    'Avondale',
    'Bloomington',
    'Allen',
    'Edinburg',
    'Pharr',
    'East Los Angeles',
    'Mission',
    'Palm Coast',
    'Wilmington',
    'Citrus Heights',
    'San Leandro',
    'Lakewood',
    'Bryan',
    'Cary',
    'Bellflower',
    'Rochester Hills',
    'Chino',
    'Redwood City',
    'Champaign',
    'Goodyear',
    'Pocatello',
    'Bismarck',
    'Youngstown',
    'Lorain',
    'Pearland',
    'Kirkland',
    'Mount Vernon',
    'Tallahassee',
    'Schenectady',
    'Casa Grande',
    'Grand Junction',
    'Charleston',
    'Cheyenne',
    'Rapid City',
    'Lauderhill',
    'Springdale',
    'Lake Forest',
    'Monterey Park',
    'St. Cloud',
    'Diamond Bar',
    'Great Falls',
    'Rock Hill',
    'Blaine',
    'Midland',
    'Bolingbrook',
    'Troy',
    'Huntersville',
    'Redmond',
    'Cathedral City',
    'Sanford',
    'Kettering',
    'Paramount',
    'Palo Alto',
    'Eagan',
    'Orem',
    'Bossier City',
    'Saginaw',
    'Mishawaka',
    'Rowlett',
    'Union City',
    'Lancaster',
    'Chesterfield',
    'Palo Alto',
    'Kokomo',
    'Chapel Hill',
    'Charleston',
    'Joplin',
    'Watsonville',
    'Kentwood',
    'Redmond',
    'Southaven',
    'Santa Fe',
    'Edmonds',
    'Eastvale',
    'Brentwood',
    'Westerville',
    'Elyria',
    'Santee',
    'Mentor',
    'Carmel',
    'Madera',
    'Rocklin',
    'Arcadia',
    'Portage',
    'Tigard',
    'Diamond Bar',
    'Novi',
    'Euless',
    'Kannapolis',
    'St. Peters',
    'Lakeville',
    'Pflugerville',
    'Carol Stream',
    'Cedar Hill',
    'Monroe',
    'New Braunfels',
    'Shawnee',
    'Lenexa',
    'San Luis Obispo',
    'Wausau',
    'Bartlett',
    'Southfield',
    'Kingsport',
    'La Quinta',
    'West Hollywood',
    'Novi',
    'Twin Falls',
    'Elmhurst',
    'Lacey',
    'Elkhart',
    'Plainfield',
    'Burien',
    'Sammamish',
    'Panama City',
    'Apache Junction',
    'Draper',
    'Adelanto',
    'Stillwater',
    'Elk Grove Village',
    'Kirkland',
    'Holyoke',
    'Huntersville',
    'Leominster',
    'North Port',
    'North Lauderdale',
    'Pinellas Park',
    'Barnstable Town',
    'Des Plaines',
    'Grapevine',
    'Hilton Head Island',
    'Oak Lawn',
    'Orland Park',
    'Attleboro',
    'Cheyenne',
    'Cerritos',
    'Cleveland Heights',
    'Columbus',
    'Farmington',
    'Farmington Hills',
    'Fort Pierce',
    'Highland',
    'Noblesville',
    'Royal Oak',
    'East Providence',
    'Portage',
    'Bremerton',
    'DeKalb',
    'Dubuque',
    'Greeley',
    'Hattiesburg',
    'Hendersonville',
    'Hoffman Estates',
    'Lombard',
    'Brookline',
    'North Richland Hills',
    'Renton',
    'San Gabriel',
    'San Ramon',
    'Schaumburg',
    'Yorba Linda',
    'Sierra Vista',
    'Warner Robins',
    'Dunwoody',
    'Eden Prairie',
    'East Point',
    'Eastvale',
    'La Mesa',
    'Laguna Niguel',
    'Orland Park',
    'Peachtree Corners',
    'San Marcos',
    'Westfield',
    'Woodland',
    'Puyallup',
    'Florence',
    'Glenview',
    'Auburn',
    'St. Clair Shores',
    'Brentwood',
    'Casper',
    'Coppell',
    'Euclid',
    'Grand Forks',
    'Grove City',
    'Hilton Head Island',
    'Wheaton',
    'Belleville',
    'Perris',
    'San Luis Obispo',
    'La Puente',
    'Moorhead',
    'Poway',
    'Rocky Mount',
    'Rogers',
    'Sanford',
    'Southaven',
    'Spokane Valley',
    'Suffolk',
    'Union City',
    'Waltham',
    'Plymouth',
    'Sarasota',
    'Wyoming',
    'Riverton',
    'Riverton',
    'Romeoville',
    'Shoreline',
    'West Sacramento',
    'St. Louis Park',
    'Highland',
    'Huntley',
    'LaGrange',
    'Lake Oswego',
    'Ormond Beach',
    'Portage',
    'West Lafayette',
    'Westland',
    'Burleson',
    'Chaska',
    'Clearfield',
    'Clovis',
    'El Centro',
    'Hickory',
    'Hobbs',
    'Lacey',
    'Lehi',
    'Logan',
    'Manhattan',
    'Monroe',
    'Oak Park',
    'Porterville',
    'Rockwall',
    'Rosemead',
    'Shakopee',
    'Sumter',
    'Watertown',
    'Wylie',
    'York',
    'Rock Springs',
    'Rocky Mount',
    'Bremerton',
    'Bullhead City',
    'Calexico',
    'Casa Grande',
    'Duncanville',
    'Hobbs',
    'Huntington Park',
    'Jackson',
    'Monroe',
    'Naperville',
    'Newark',
    'Niagara Falls',
    'Owensboro',
    'Pocatello',
    'Rome',
    'Sammamish',
    'Sandy',
    'South San Francisco',
    'Wheaton',
    'White Plains',
    'Yorba Linda',
    'Youngstown',
    'Bartlett',
    'Casa Grande',
    'Duncanville',
    'Huntington Park',
    'Jackson',
    'Naperville',
    'Newark',
    'Niagara Falls',
    'Owensboro',
    'Pocatello',
    'Sammamish',
    'South San Francisco',
    'Wheaton',
    'White Plains',
    'Carson City',
    'Elko',
    'Henderson',
    'North Las Vegas',
    'Reno',
    'Sparks',
    'La Vergne',
    'Franklin',
    'Brentwood',
    'Smyrna',
    'Aventura',
    'Coral Gables',
    'Coral Springs',
    'Fort Myers',
    'Fort Pierce',
    'North Miami Beach',
    'Ocala',
    'Palm Bay',
    'Palm Coast',
    'Port Orange',
    'Sarasota',
    'Weston',
    'Boise City',
    'Caldwell',
    'Coeur d\'Alene',
    'Eagle',
    'Idaho Falls',
    'Kuna',
    'Lewiston',
    'Meridian',
    'Moscow',
    'Nampa',
    'Pocatello',
    'Post Falls',
    'Rexburg',
    'Twin Falls',
    'Billings',
    'Bozeman',
    'Great Falls',
    'Helena',
    'Kalispell',
    'Missoula',
    'Bismarck',
    'Dickinson',
    'Fargo',
    'Grand Forks',
    'Jamestown',
    'Mandan',
    'Minot',
    'West Fargo',
    'Bowling Green',
    'Covington',
    'Elizabethtown',
    'Florence',
    'Frankfort',
    'Georgetown',
    'Henderson',
    'Hopkinsville',
    'Jeffersontown',
    'Lexington-Fayette',
    'Louisville',
    'Nicholasville',
    'Owensboro',
    'Paducah',
    'Radcliff',
    'Richmond',
    'Baton Rouge',
    'Bossier City',
    'Kenner',
    'Lafayette',
    'Lake Charles',
    'Monroe',
    'New Orleans',
    'Shreveport',
    'Portland',
    'South Portland',
    'Lewiston',
    'Bangor',
    'Biddeford',
    'Sanford',
    'Saco',
    'Augusta',
    'Westbrook',
    'Waterville',
    'Auburn',
    'Presque Isle',
    'Marysville',
    'Anacortes',
    'Arlington',
    'Auburn',
    'Bainbridge Island',
    'Battle Ground',
    'Bellevue',
    'Bellingham',
    'Bonney Lake',
    'Bothell',
    'Bremerton',
    'Burien',
    'Camas',
    'Centralia',
    'Chehalis',
    'Covington',
    'Des Moines',
    'Edmonds',
    'Ellensburg',
    'Enumclaw',
    'Everett',
    'Federal Way',
    'Ferndale',
    'Gig Harbor',
    'Issaquah',
    'Kenmore',
    'Kennewick',
    'Kent',
    'Kirkland',
    'Lacey',
    'Lake Forest Park',
    'Lake Stevens',
    'Lakewood',
    'Longview',
    'Lynnwood',
    'Maple Valley',
    'Marysville',
    'Mercer Island',
    'Mill Creek',
    'Monroe',
    'Moses Lake',
    'Mount Vernon',
    'Mountlake Terrace',
    'Mukilteo',
    'North Bend',
    'Oak Harbor',
    'Olympia',
    'Pasco',
    'Port Angeles',
    'Port Orchard',
    'Poulsbo',
    'Pullman',
    'Puyallup',
    'Redmond',
    'Renton',
    'Richland',
    'Sammamish',
    'SeaTac',
    'Seattle',
    'Shoreline',
    'Silverdale',
    'Snohomish',
    'Spanaway',
    'Spokane',
    'Sumner',
    'Tacoma',
    'Tukwila',
    'Tumwater',
    'University Place',
    'Vancouver',
    'Walla Walla',
    'Washougal',
    'Wenatchee',
    'West Richland',
    'Woodinville',
    'Yakima',
    'Appleton',
    'Beloit',
    'Brookfield',
    'Caledonia',
    'Cudahy',
    'De Pere',
    'Fitchburg',
    'Fond du Lac',
    'Franklin',
    'Germantown',
    'Green Bay',
    'Greenfield',
    'Howard',
    'Janesville',
    'Kaukauna',
    'Kenosha',
    'La Crosse',
    'Madison',
    'Manitowoc',
    'Marinette',
    'Marshfield',
    'Menasha',
    'Menomonee Falls',
    'Menomonie',
    'Mequon',
    'Middleton',
    'Milwaukee',
    'Muskego',
    'Neenah',
    'New Berlin',
    'Oak Creek',
    'Oconomowoc',
    'Onalaska',
    'Oshkosh',
    'Pleasant Prairie',
    'Racine',
    'River Falls',
    'Sheboygan',
    'Shorewood',
    'South Milwaukee',
    'Stevens Point',
    'Stoughton',
    'Sun Prairie',
    'Superior',
    'Two Rivers',
    'Watertown',
    'Waukesha',
    'Waunakee',
    'Waupun',
    'Wausau',
    'Wauwatosa',
    'West Allis',
    'West Bend',
    'Whitewater',
    'Altoona',
    'Ankeny',
    'Bettendorf',
    'Burlington',
    'Cedar Falls',
    'Cedar Rapids',
    'Clinton',
    'Clive',
    'Coralville',
    'Council Bluffs',
    'Davenport',
    'Des Moines',
    'Dubuque',
    'Fort Dodge',
    'Indianola',
    'Iowa City',
    'Johnston',
    'Marion',
    'Marshalltown',
    'Mason City',
    'Muscatine',
    'Newton',
    'North Liberty',
    'Ottumwa',
    'Sioux City',
    'Urbandale',
    'Waterloo',
    'West Des Moines',
    'Derby',
    'Emporia',
    'Garden City',
    'Hays',
    'Hutchinson',
    'Junction City',
    'Kansas City',
    'Lawrence',
    'Leavenworth',
    'Leawood',
    'Lenexa',
    'Manhattan',
    'Newton',
    'Olathe',
    'Overland Park',
    'Pittsburg',
    'Prairie Village',
    'Salina',
    'Shawnee',
    'Topeka',
    'Wichita',
    'Ashland',
    'Bowling Green',
    'Covington',
    'Danville',
    'Elizabethtown',
    'Erlanger',
    'Florence',
    'Fort Thomas',
    'Frankfort',
    'Georgetown',
    'Henderson',
    'Hopkinsville',
    'Independence',
    'Jeffersontown',
    'Lexington-Fayette',
    'Louisville',
    'Madisonville',
    'Murray',
    'Newport',
    'Nicholasville',
    'Owensboro',
    'Paducah',
    'Radcliff',
    'Richmond',
    'Shelbyville',
    'Shively',
    'St. Matthews',
    'Winchester',
    'Alexandria',
    'Baton Rouge',
    'Bayou Cane',
    'Bossier City',
    'Central',
    'Chalmette',
    'Estelle',
    'Gretna',
    'Hammond',
    'Harvey',
    'Houma',
    'Kenner',
    'Lafayette',
    'Lake Charles',
    'Laplace',
    'Marrero',
    'Metairie',
    'Monroe',
    'Natchitoches',
    'New Iberia',
    'New Orleans',
    'Opelousas',
    'Pineville',
    'Ruston',
    'Shenandoah',
    'Shreveport',
    'Slidell',
    'Sulphur',
    'Terrytown',
    'Zachary',
    'Biloxi',
    'Brandon',
    'Clarksdale',
    'Clinton',
    'Columbus',
    'Gautier',
    'Greenville',
    'Greenwood',
    'Gulfport',
    'Hattiesburg',
    'Hernando',
    'Horn Lake',
    'Indianola',
    'Jackson',
    'Long Beach',
    'Madison',
    'Meridian',
    'Moss Point',
    'Natchez',
    'Ocean Springs',
    'Olive Branch',
    'Oxford',
    'Pascagoula',
    'Pearl',
    'Petal',
    'Philadelphia',
    'Picayune',
    'Richland',
    'Ridgeland',
    'Southaven',
    'Starkville',
    'Tupelo',
    'Vicksburg',
    'West Point',
    'Albany',
    'Amsterdam',
    'Auburn',
    'Batavia',
    'Beacon',
    'Binghamton',
    'Buffalo',
    'Canandaigua',
    'Cohoes',
    'Corning',
    'Cortland',
    'Dunkirk',
    'Elmira',
    'Fulton',
    'Geneva',
    'Glen Cove',
    'Glens Falls',
    'Gloversville',
    'Hornell',
    'Hudson',
    'Ithaca',
    'Jamestown',
    'Johnstown',
    'Kingston',
    'Lackawanna',
    'Little Falls',
    'Lockport',
    'Long Beach',
    'Mechanicville',
    'Middletown',
    'Mount Vernon',
    'New Rochelle',
    'New York',
    'Newburgh',
    'Niagara Falls',
    'North Tonawanda',
    'Norwich',
    'Ogdensburg',
    'Olean',
    'Oneida',
    'Oneonta',
    'Oswego',
    'Peekskill',
    'Plattsburgh',
    'Port Jervis',
    'Poughkeepsie',
    'Rensselaer',
    'Rochester',
    'Rome',
    'Rye',
    'Salamanca',
    'Saratoga Springs',
    'Schenectady',
    'Sherrill',
    'Syracuse',
    'Tonawanda',
    'Troy',
    'Utica',
    'Watertown',
    'Watervliet',
    'White Plains',
    'Yonkers',
    'Asheville',
    'Burlington',
    'Charlotte',
    'Concord',
    'Durham',
    'Fayetteville',
    'Gastonia',
    'Goldsboro',
    'Greensboro',
    'Greenville',
    'Hickory',
    'High Point',
    'Jacksonville',
    'Kannapolis',
    'Raleigh',
    'Rocky Mount',
    'Wilmington',
    'Wilson',
    'Winston-Salem',
    'Bismarck',
    'Dickinson',
    'Fargo',
    'Grand Forks',
    'Jamestown',
    'Mandan',
    'Minot',
    'West Fargo',
    'Akron',
    'Alliance',
    'Ashland',
    'Ashtabula',
    'Athens',
    'Aurora',
    'Avon Lake',
    'Barberton',
    'Bay Village',
    'Beachwood',
    'Beavercreek',
    'Bedford',
    'Bedford Heights',
    'Bellbrook',
    'Bellefontaine',
    'Bellevue',
    'Belpre',
    'Berea',
    'Bexley',
    'Blue Ash',
    'Bowling Green',
    'Brecksville',
    'Brook Park',
    'Brooklyn',
    'Brooklyn Heights',
    'Brookville',
    'Brunswick',
    'Bryan',
    'Bucyrus',
    'Cambridge',
    'Campbell',
    'Canal Fulton',
    'Canal Winchester',
    'Canfield',
    'Canton',
    'Carlisle',
    'Celina',
    'Centerville',
    'Chardon',
    'Cheviot',
    'Chillicothe',
    'Cincinnati',
    'Circleville',
    'Clayton',
    'Cleveland',
    'Cleveland Heights',
    'Clyde',
    'Columbus',
    'Conneaut',
    'Cortland',
    'Coshocton',
    'Covington',
    'Crestline',
    'Cuyahoga Falls',
    'Dayton',
    'Deer Park',
    'Defiance',
    'Delaware',
    'Delphos',
    'Dover',
    'Dublin',
    'East Cleveland',
    'East Liverpool',
    'Eastlake',
    'Eaton',
    'Elyria',
    'Englewood',
    'Euclid',
    'Fairborn',
    'Fairfield',
    'Fairlawn',
    'Fairview Park',
    'Findlay',
    'Forest Park',
    'Fostoria',
    'Franklin',
    'Fremont',
    'Gahanna',
    'Galion',
    'Garfield Heights',
    'Geneva',
    'Germantown',
    'Girard',
    'Grandview Heights',
    'Green',
    'Greenville',
    'Grove City',
    'Groveport',
    'Hamilton',
    'Heath',
    'Highland Heights',
    'Hilliard',
    'Hillsboro',
    'Hubbard',
    'Huber Heights',
    'Hudson',
    'Huron',
    'Independence',
    'Ironton',
    'Jackson',
    'Jefferson',
    'Kent',
    'Kenton',
    'Kettering',
    'Kirtland',
    'Lakewood',
    'Lancaster',
    'Lebanon',
    'Leetonia',
    'Lima',
    'Logan',
    'London',
    'Lorain',
    'Louisville',
    'Loveland',
    'Lyndhurst',
    'Macedonia',
    'Madeira',
    'Madison',
    'Mansfield',
  ];
}